### ISSUE TITLE
Modeline for Bad Dudes vs Dragonninja

### ISSUE THREAD

**Issue by thehughhefner** [atrac17/MiSTer_Integer_Modelines#2]
Hi Atrac,
Could you include modelines for bad dudes vs dragonninja?

**Comment by atrac17** [comment]
I'll post DECO MEC-1M video modes soon. Since it's 240p it really wasn't a priority at the time.

**Comment by atrac17** [comment]
[Done](https://github.com/atrac17/MiSTer_Integer_Modelines/commit/2462dbc2f6b7805fb1eebd094a149a783545580d).

**Comment by thehughhefner** [comment]
Thank you :)
